### ISSUE TITLE
brew upgrade to 3.2 error

### ISSUE THREAD

**Issue by misato** [pebble/homebrew-pebble-sdk#24] opened 2015-07-25 15:43 UTC
I get this error when upgrading from the SDK 3.1 to 3.2:

######################################################################## 100,0%
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1317, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1381, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in /usr/local/Cellar/pebble-sdk/3.2/libexec/lib/python2.7/site-packages/pyasn1_modules-0.0.5-py2.7.egg

**Comment by cjwilliams** [comment] 2015-07-25 16:53
Duplicate of #20, please see comments

**Closed by cjwilliams** 2015-07-25 16:53 UTC
Labels: duplicate
