### ISSUE TITLE
libev in gevent 1.0.2 cannot build on OS X 10.11

### ISSUE THREAD

**Issue by medicalwei** [pebble/homebrew-pebble-sdk#19] opened 2015-07-15 00:44 UTC
I am sorry to live on the bleeding edge, but libev in gevent 1.0.2 cannot build on OS X 10.11

It can be installed by upgrading the dependency to gevent 1.1a2, but I didn't test it thoroughly.

**Comment by Katharine** [comment] 2015-07-15 04:17
We're probably going to hold off on this until it's out of alpha.

**Comment by cjwilliams** [comment] 2015-07-25 01:03
Duplicate of #18

**Closed by cjwilliams** 2015-07-25 01:03 UTC
Labels: duplicate
