### ISSUE TITLE
Brew upgrade fails when upgrading to 3.2 from 3.1

### ISSUE THREAD

**Issue by johanhammar** [pebble/homebrew-pebble-sdk#21] opened 2015-07-23 20:23 UTC
Upgrading pebble-sdk to 3.2 gives this error: 

```
$ brew upgrade
==> Upgrading 1 outdated package, with result:
pebble/pebble-sdk/pebble-sdk 3.2
==> Upgrading pebble/pebble-sdk/pebble-sdk
==> Downloading https://sdk.getpebble.com/download/3.2?source=homebrew
Already downloaded: /Library/Caches/Homebrew/pebble-sdk-3.2.2
==> Downloading https://pypi.python.org/packages/source/b/backports.ssl_match_hostname/backports.ssl_match_hostname-3.4.
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--backports.ssl-match-hostname-3.4.0.2.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/c/colorama/colorama-0.3.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--colorama-0.3.3.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/e/enum34/enum34-1.0.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--enum34-1.0.4.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/f/freetype-py/freetype-py-1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--freetype-py-1.0.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/g/gevent/gevent-1.0.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--gevent-1.0.2.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/g/gevent-websocket/gevent-websocket-0.9.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--gevent-websocket-0.9.3.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/g/greenlet/greenlet-0.4.7.zip
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--greenlet-0.4.7.zip
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/h/httplib2/httplib2-0.9.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--httplib2-0.9.1.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/l/libpebble2/libpebble2-0.0.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--libpebble2-0.0.7.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/o/oauth2client/oauth2client-1.4.11.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--oauth2client-1.4.11.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/p/peewee/peewee-2.4.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--peewee-2.4.7.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/p/progressbar2/progressbar2-2.7.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--progressbar2-2.7.3.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/p/pyasn1/pyasn1-0.1.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--pyasn1-0.1.7.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
==> Downloading https://pypi.python.org/packages/source/p/pyasn1-modules/pyasn1-modules-0.0.5.tar.gz
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--pyasn1-modules-0.0.5.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1317, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1381, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in /usr/local/Cellar/pebble-sdk/3.2/libexec/lib/python2.7/site-packages/pyasn1_modules-0.0.5-py2.7.egg
```

**Comment by cjwilliams** [comment] 2015-07-23 20:33
Duplicate of #20

**Closed by cjwilliams** 2015-07-23 20:33 UTC
Labels: duplicate
